AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - examples/*
    - spec/*
  NewCops: disable

Layout:
  Enabled: False

# Increases "Line is too long" warning from 80 tp 200
Layout/LineLength:
  Max: 250
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# Increases "Class definition is too long" warning from 100 to 200
Metrics/ClassLength:
  Max: 200

# Increases "Method has too many lines" warning from 10 to 75
Metrics/MethodLength:
  Max: 98

# Increases "Module has too many lines" warning from 100 to 300
Metrics/ModuleLength:
  Max: 300

# Increases "Assignment Branch Condition size" warning from 15 to 80
Metrics/AbcSize:
  Max: 100

# Increases "Block has too many lines" warning from 25 to 190
Metrics/BlockLength:
  Max: 190

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Disables "Use nested module/class definitions instead of compact style" warning
Style/ClassAndModuleChildren:
  Enabled: false

# Disables "Missing top-level class documentation comment" warning
Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/OptionalBooleanParameter:
  AllowedMethods: [playlist_items, delete_playlist]

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RescueStandardError:
  Enabled: False
